# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('qualification', models.CharField(choices=[('ug', 'UnderGraduate'), ('pg', 'PostGraduate'), ('phd', 'PHD'), ('fac', 'faculty'), ('ind', 'industrial')], default=None, max_length=10)),
                ('university', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
