# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171107_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
