# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20171108_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(choices=[('ug', 'UnderGraduate'), ('pg', 'PostGraduate'), ('phd', 'PhD'), ('fac', 'Faculty'), ('ind', 'Industrial'), ('No', 'None')], default='No', max_length=10)),
                ('university', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
