# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171108_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
