# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userpro_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='image',
        ),
    ]
