# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userpro_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Userpro')),
            ],
        ),
    ]
