# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('code', models.CharField(max_length=100)),
                ('is_prize', models.BooleanField(default=False)),
                ('is_goodies', models.BooleanField(default=False)),
                ('goofies', models.CharField(default=None, max_length=100)),
                ('first_prize', models.IntegerField(default=0)),
                ('second_prize', models.IntegerField(default=0)),
                ('third_prize', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Userpro')),
            ],
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
